### ISSUE TITLE
Run docker CI stage only on master

### ISSUE THREAD

**Issue by devdinu** [gojek/beast#21]
currently `Deploy` stage is failing in travis for branches. It should be run only on `master` branch.

**Comment by yohei1126** [comment]
Do you wanna run Travis build only on `master` branch?

**Comment by devdinu** [comment]
We should run `deploy` stage only on master. build/test should run on all branches.

**Comment by yohei1126** [comment]
thanks. I am new to travis but will work on it.

**Comment by yohei1126** [comment]
travis.yml already has conditional stage configuration....
```
stages:
  - test
  - name: deploy
    if: branch == master
```
